#!/usr/bin/env bash
set -e
set -o xtrace

function usage {
    echo "USAGE: $0 <source-dir> <target-dir> <ip-list> <user>"
    echo "  example: $0 ./certificates /etc/kubernetes/ssl 127.0.0.1,10.0.0.1 core"
}

if [ -z "$1" ] || [ -z "$2" ] || [ -z "$3" ] || [ -z "$4" ]; then
    usage
    exit 1
fi

SOURCE="$1"
TARGET="$2"
IPS="$3"
USER="$4"

export IFS=","
for ip in $IPS; do
	echo "Deploying into $ip"
	ssh "$USER"@"$ip" "if [ ! -d $TARGET ]; then sudo mkdir -m 755 -p $TARGET && sudo chown $USER:$USER $TARGET;fi"
	echo "Copying certificates"
  	scp "$SOURCE"/* "$USER"@"$ip":"$TARGET"
done